namespace TlsLib
{
    public static class Constaints
    {
        public static readonly List<TlsClientIdentifier> BrowserTlsIdentifiers = new()
        {
            TlsClientIdentifier.Chrome_103,
            TlsClientIdentifier.Chrome_104,
            TlsClientIdentifier.Chrome_105,
            TlsClientIdentifier.Chrome_106,
            TlsClientIdentifier.Chrome_107,
            TlsClientIdentifier.Chrome_108,
            TlsClientIdentifier.Chrome_109,
            TlsClientIdentifier.Chrome_110,
            TlsClientIdentifier.Chrome_111,
            TlsClientIdentifier.Chrome_112,
            TlsClientIdentifier.Chrome_116_PSK,
            TlsClientIdentifier.Chrome_116_PSK_PQ,
            TlsClientIdentifier.Chrome_117,
            TlsClientIdentifier.Chrome_120,
            TlsClientIdentifier.Chrome_124,
            TlsClientIdentifier.Safari_15_6_1,
            TlsClientIdentifier.Safari_16_0,
            TlsClientIdentifier.Safari_Ipad_15_6,
            TlsClientIdentifier.Safari_IOS_15_5,
            TlsClientIdentifier.Safari_IOS_15_6,
            TlsClientIdentifier.Safari_IOS_16_0,
            TlsClientIdentifier.Safari_IOS_17_0,
            TlsClientIdentifier.Firefox_102,
            TlsClientIdentifier.Firefox_104,
            TlsClientIdentifier.Firefox_105,
            TlsClientIdentifier.Firefox_106,
            TlsClientIdentifier.Firefox_108,
            TlsClientIdentifier.Firefox_110,
            TlsClientIdentifier.Firefox_117,
            TlsClientIdentifier.Firefox_120,
            TlsClientIdentifier.Firefox_123,
            TlsClientIdentifier.Opera_89,
            TlsClientIdentifier.Opera_90,
            TlsClientIdentifier.Opera_91
        };

        public static readonly Dictionary<TlsClientIdentifier, string> TlsClientIdentifiersDictionary = new()
        {
            { TlsClientIdentifier.Chrome_103, "chrome_103" },
            { TlsClientIdentifier.Chrome_104, "chrome_104" },
            { TlsClientIdentifier.Chrome_105, "chrome_105" },
            { TlsClientIdentifier.Chrome_106, "chrome_106" },
            { TlsClientIdentifier.Chrome_107, "chrome_107" },
            { TlsClientIdentifier.Chrome_108, "chrome_108" },
            { TlsClientIdentifier.Chrome_109, "chrome_109" },
            { TlsClientIdentifier.Chrome_110, "chrome_110" },
            { TlsClientIdentifier.Chrome_111, "chrome_111" },
            { TlsClientIdentifier.Chrome_112, "chrome_112" },
            { TlsClientIdentifier.Chrome_116_PSK, "chrome_116_PSK" },
            { TlsClientIdentifier.Chrome_116_PSK_PQ, "chrome_116_PSK_PQ" },
            { TlsClientIdentifier.Chrome_117, "chrome_117" },
            { TlsClientIdentifier.Chrome_120, "chrome_120" },
            { TlsClientIdentifier.Chrome_124, "chrome_124" },
            { TlsClientIdentifier.Safari_15_6_1, "safari_15_6_1" },
            { TlsClientIdentifier.Safari_16_0, "safari_16_0" },
            { TlsClientIdentifier.Safari_Ipad_15_6, "safari_ipad_15_6" },
            { TlsClientIdentifier.Safari_IOS_15_5, "safari_ios_15_5" },
            { TlsClientIdentifier.Safari_IOS_15_6, "safari_ios_15_6" },
            { TlsClientIdentifier.Safari_IOS_16_0, "safari_ios_16_0" },
            { TlsClientIdentifier.Safari_IOS_17_0, "safari_ios_17_0" },
            { TlsClientIdentifier.Firefox_102, "firefox_102" },
            { TlsClientIdentifier.Firefox_104, "firefox_104" },
            { TlsClientIdentifier.Firefox_105, "firefox_105" },
            { TlsClientIdentifier.Firefox_106, "firefox_106" },
            { TlsClientIdentifier.Firefox_108, "firefox_108" },
            { TlsClientIdentifier.Firefox_110, "firefox_110" },
            { TlsClientIdentifier.Firefox_117, "firefox_117" },
            { TlsClientIdentifier.Firefox_120, "firefox_120" },
            { TlsClientIdentifier.Firefox_123, "firefox_123" },
            { TlsClientIdentifier.Opera_89, "opera_89" },
            { TlsClientIdentifier.Opera_90, "opera_90" },
            { TlsClientIdentifier.Opera_91, "opera_91" },
            { TlsClientIdentifier.ZalandoAndroidMobile, "zalando_android_mobile" },
            { TlsClientIdentifier.ZalandoIosMobile, "zalando_ios_mobile" },
            { TlsClientIdentifier.NikeIosMobile, "nike_ios_mobile" },
            { TlsClientIdentifier.NikeAndroidMobile, "nike_android_mobile" },
            { TlsClientIdentifier.CloudflareCustom, "cloudscraper" },
            { TlsClientIdentifier.MMSIos, "mms_ios" },
            { TlsClientIdentifier.MMSIos2, "mms_ios_2" },
            { TlsClientIdentifier.MMSIos3, "mms_ios_3" },
            { TlsClientIdentifier.MeshIos, "mesh_ios" },
            { TlsClientIdentifier.MeshIos2, "mesh_ios_2" },
            { TlsClientIdentifier.MeshAndroid, "mesh_android" },
            { TlsClientIdentifier.MeshAndroid2, "mesh_android_2" },
            { TlsClientIdentifier.ConfirmedIos, "confirmed_ios" },
            { TlsClientIdentifier.ConfirmedAndroid, "confirmed_android" },
            { TlsClientIdentifier.Okhttp4Android7, "okhttp4_android_7" },
            { TlsClientIdentifier.Okhttp4Android8, "okhttp4_android_8" },
            { TlsClientIdentifier.Okhttp4Android9, "okhttp4_android_9" },
            { TlsClientIdentifier.Okhttp4Android10, "okhttp4_android_10" },
            { TlsClientIdentifier.Okhttp4Android11, "okhttp4_android_11" },
            { TlsClientIdentifier.Okhttp4Android12, "okhttp4_android_12" },
            { TlsClientIdentifier.Okhttp4Android13, "okhttp4_android_13" }
        };
    }
}
